// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayrollManagementSystem.Infrastructure.Persistence;

#nullable disable

namespace PayrollManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260711115818_AddAuditingFields")]
    partial class AddAuditingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.BacLuong", b =>
                {
                    b.Property<string>("IdBacLuong")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_bac_luong");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("IdNgachLuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_ngach_luong");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LuongP1")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("luong_p1");

                    b.Property<DateOnly>("NgayApDung")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ap_dung");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TenBacLuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_bac_luong");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdBacLuong")
                        .HasName("bac_luongs_pkey");

                    b.HasIndex("IdNgachLuong");

                    b.ToTable("bac_luongs", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ChiTietDanhGiaNangLuc", b =>
                {
                    b.Property<Guid>("IdChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_chi_tiet")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("DiemQuanLyDanhGia")
                        .HasColumnType("integer")
                        .HasColumnName("diem_quan_ly_danh_gia");

                    b.Property<int?>("DiemTuDanhGia")
                        .HasColumnType("integer")
                        .HasColumnName("diem_tu_danh_gia");

                    b.Property<Guid>("IdPhieu")
                        .HasColumnType("uuid")
                        .HasColumnName("id_phieu");

                    b.Property<Guid>("IdTieuChi")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tieu_chi");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NhanXetNhanVien")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nhan_xet_nhan_vien");

                    b.Property<string>("NhanXetQuanLy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nhan_xet_quan_ly");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdChiTiet")
                        .HasName("chi_tiet_danh_gia_nang_lucs_pkey");

                    b.HasIndex("IdPhieu");

                    b.HasIndex("IdTieuChi");

                    b.ToTable("chi_tiet_danh_gia_nang_lucs", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ChucVu", b =>
                {
                    b.Property<string>("IdChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_chuc_vu");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("IdChucVuQuanLy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_chuc_vu_quan_ly");

                    b.Property<string>("IdNgachLuong")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_ngach_luong");

                    b.Property<string>("IdPhongBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_phong_ban");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTaCongViec")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mo_ta_cong_viec");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_chuc_vu");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdChucVu")
                        .HasName("chuc_vus_pkey");

                    b.HasIndex("IdChucVuQuanLy");

                    b.HasIndex("IdNgachLuong");

                    b.HasIndex("IdPhongBan");

                    b.ToTable("chuc_vus", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.HopDongLaoDong", b =>
                {
                    b.Property<string>("SoHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_hop_dong");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("loai_hop_dong");

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("luong_co_ban");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("SoHopDong")
                        .HasName("hop_dong_lao_dongs_pkey");

                    b.HasIndex("Cccd");

                    b.ToTable("hop_dong_lao_dongs", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.KhungNangLucP2", b =>
                {
                    b.Property<Guid>("IdTieuChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_tieu_chi")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("IdChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_chuc_vu");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenNangLuc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ten_nang_luc");

                    b.Property<decimal>("TyTrong")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ty_trong");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdTieuChi")
                        .HasName("khung_nang_luc_p2_pkey");

                    b.HasIndex("IdChucVu");

                    b.ToTable("khung_nang_luc_p2", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.KyDanhGia", b =>
                {
                    b.Property<Guid>("IdKyDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_ky_danh_gia")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Nam")
                        .HasColumnType("integer")
                        .HasColumnName("nam");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TenKyDanhGia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_ky_danh_gia");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdKyDanhGia")
                        .HasName("ky_danh_gias_pkey");

                    b.ToTable("ky_danh_gias", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.MoiQuanHe", b =>
                {
                    b.Property<Guid>("IdMqh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_mqh")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenQuanHe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_quan_he");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdMqh")
                        .HasName("moi_quan_hes_pkey");

                    b.ToTable("moi_quan_hes", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.MucQuyDoiP2", b =>
                {
                    b.Property<Guid>("IdQuyDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_quy_doi")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiemToiDa")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("diem_toi_da");

                    b.Property<decimal>("DiemToiThieu")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("diem_toi_thieu");

                    b.Property<decimal>("HeSoP2")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("he_so_p2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("XepLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("xep_loai");

                    b.HasKey("IdQuyDoi")
                        .HasName("muc_quy_doi_p2s_pkey");

                    b.ToTable("muc_quy_doi_p2s", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NgachLuong", b =>
                {
                    b.Property<string>("IdNgachLuong")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_ngach_luong");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenNgachLuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_ngach_luong");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdNgachLuong")
                        .HasName("ngach_luongs_pkey");

                    b.ToTable("ngach_luongs", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhanVien", b =>
                {
                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chuyen_nganh");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DanToc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dan_toc");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("boolean")
                        .HasColumnName("gioi_tinh");

                    b.Property<decimal?>("HeSoP2")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("he_so_p2");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("IdPb")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_pb");

                    b.Property<Guid?>("IdTaiKhoan")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ma_so_thue");

                    b.Property<DateOnly?>("NgayNghiViec")
                        .HasColumnType("date")
                        .HasColumnName("ngay_nghi_viec");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateOnly?>("NgayVaoLam")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_lam");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("SoBhxh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_bhxh");

                    b.Property<string>("SoBhyt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_bhyt");

                    b.Property<string>("SoTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_tai_khoan");

                    b.Property<string>("TenNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_ngan_hang");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Cccd")
                        .HasName("nhan_viens_pkey");

                    b.HasIndex("IdPb");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "nhan_viens_email_key")
                        .IsUnique();

                    b.ToTable("nhan_viens", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhatKyTrangThai", b =>
                {
                    b.Property<Guid>("IdNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_nhat_ky")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ly_do");

                    b.Property<DateTime>("NgayThayDoi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_thay_doi");

                    b.Property<string>("NguoiThayDoi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nguoi_thay_doi");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai_cu");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai_moi");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdNhatKy")
                        .HasName("nhat_ky_trang_thais_pkey");

                    b.HasIndex("Cccd");

                    b.ToTable("nhat_ky_trang_thais", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.PhieuDanhGiaNangLuc", b =>
                {
                    b.Property<Guid>("IdPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_phieu")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CccdNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd_nhan_vien");

                    b.Property<string>("CccdQuanLy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd_quan_ly");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DiemTongHop")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("diem_tong_hop");

                    b.Property<decimal?>("HeSoP2")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("he_so_p2");

                    b.Property<Guid>("IdKyDanhGia")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ky_danh_gia");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NhanXetChung")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("nhan_xet_chung");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("XepLoai")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("xep_loai");

                    b.HasKey("IdPhieu")
                        .HasName("phieu_danh_gia_nang_lucs_pkey");

                    b.HasIndex("CccdNhanVien");

                    b.HasIndex("CccdQuanLy");

                    b.HasIndex("IdKyDanhGia");

                    b.ToTable("phieu_danh_gia_nang_lucs", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.PhongBan", b =>
                {
                    b.Property<string>("IdPb")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_pb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenPb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_pb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdPb")
                        .HasName("phong_bans_pkey");

                    b.ToTable("phong_bans", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.QuyetDinhNhanSu", b =>
                {
                    b.Property<string>("SoQuyetDinh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_quyet_dinh");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("IdBacLuongMoi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_bac_luong_moi");

                    b.Property<string>("IdChucVuMoi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_chuc_vu_moi");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LoaiQuyetDinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("loai_quyet_dinh");

                    b.Property<DateOnly?>("NgayHetHan")
                        .HasColumnType("date")
                        .HasColumnName("ngay_het_han");

                    b.Property<DateOnly>("NgayHieuLuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_hieu_luc");

                    b.Property<string>("NguoiKy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nguoi_ky");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("SoQuyetDinh")
                        .HasName("quyet_dinh_nhan_sus_pkey");

                    b.HasIndex("Cccd");

                    b.HasIndex("IdBacLuongMoi");

                    b.ToTable("quyet_dinh_nhan_sus", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_tai_khoan");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool?>("DangNhapLanDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("dang_nhap_lan_dau");

                    b.Property<Guid?>("IdVaiTro")
                        .HasColumnType("uuid")
                        .HasColumnName("id_vai_tro");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mat_khau_hash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ten_tai_khoan");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdTaiKhoan")
                        .HasName("tai_khoans_pkey");

                    b.HasIndex("IdVaiTro");

                    b.HasIndex(new[] { "TenTaiKhoan" }, "tai_khoans_ten_tai_khoan_key")
                        .IsUnique();

                    b.ToTable("tai_khoans", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ThanNhan", b =>
                {
                    b.Property<string>("MaDinhDanh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ma_dinh_danh");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("TenTn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ten_tn");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("MaDinhDanh")
                        .HasName("than_nhans_pkey");

                    b.ToTable("than_nhans", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ThanNhanNhanVien", b =>
                {
                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("MaDinhDanh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ma_dinh_danh");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdMqh")
                        .HasColumnType("uuid")
                        .HasColumnName("id_mqh");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Cccd", "MaDinhDanh")
                        .HasName("than_nhan_nhan_vien_pkey");

                    b.HasIndex("IdMqh");

                    b.HasIndex("MaDinhDanh");

                    b.ToTable("than_nhan_nhan_vien", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.VaiTro", b =>
                {
                    b.Property<Guid>("IdVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_vai_tro");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_vai_tro");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("IdVaiTro")
                        .HasName("vai_tros_pkey");

                    b.ToTable("vai_tros", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.BacLuong", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NgachLuong", "NgachLuong")
                        .WithMany("BacLuongs")
                        .HasForeignKey("IdNgachLuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bac_luongs_id_ngach_luong_fkey");

                    b.Navigation("NgachLuong");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ChiTietDanhGiaNangLuc", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.PhieuDanhGiaNangLuc", "PhieuDanhGia")
                        .WithMany("ChiTietDanhGias")
                        .HasForeignKey("IdPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chi_tiet_danh_gias_id_phieu_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.KhungNangLucP2", "TieuChi")
                        .WithMany()
                        .HasForeignKey("IdTieuChi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chi_tiet_danh_gias_id_tieu_chi_fkey");

                    b.Navigation("PhieuDanhGia");

                    b.Navigation("TieuChi");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ChucVu", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.ChucVu", "ChucVuQuanLy")
                        .WithMany("ChucVuCapDuois")
                        .HasForeignKey("IdChucVuQuanLy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("chuc_vus_id_chuc_vu_quan_ly_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.NgachLuong", "NgachLuong")
                        .WithMany("ChucVus")
                        .HasForeignKey("IdNgachLuong")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("chuc_vus_id_ngach_luong_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("IdPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chuc_vus_id_phong_ban_fkey");

                    b.Navigation("ChucVuQuanLy");

                    b.Navigation("NgachLuong");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.HopDongLaoDong", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("HopDongLaoDongs")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hop_dong_lao_dongs_cccd_fkey");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.KhungNangLucP2", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.ChucVu", "ChucVu")
                        .WithMany("KhungNangLucs")
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("khung_nang_luc_id_chuc_vu_fkey");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhanVien", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdPb")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("nhan_viens_id_pb_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("PayrollManagementSystem.Domain.Models.NhanVien", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("nhan_viens_id_tai_khoan_fkey");

                    b.Navigation("PhongBan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhatKyTrangThai", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("NhatKyTrangThais")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("nhat_ky_trang_thais_cccd_fkey");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.PhieuDanhGiaNangLuc", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("CccdNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("phieu_danh_gias_cccd_nhan_vien_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "QuanLy")
                        .WithMany()
                        .HasForeignKey("CccdQuanLy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("phieu_danh_gias_cccd_quan_ly_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.KyDanhGia", "KyDanhGia")
                        .WithMany("PhieuDanhGias")
                        .HasForeignKey("IdKyDanhGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("phieu_danh_gias_id_ky_danh_gia_fkey");

                    b.Navigation("KyDanhGia");

                    b.Navigation("NhanVien");

                    b.Navigation("QuanLy");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.QuyetDinhNhanSu", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("QuyetDinhNhanSus")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("quyet_dinh_nhan_sus_cccd_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.BacLuong", "BacLuong")
                        .WithMany("QuyetDinhNhanSus")
                        .HasForeignKey("IdBacLuongMoi")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("quyet_dinh_nhan_sus_id_bac_luong_moi_fkey");

                    b.Navigation("BacLuong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiKhoan", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdVaiTro")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("tai_khoans_id_vai_tro_fkey");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ThanNhanNhanVien", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("ThanNhanNhanViens")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("than_nhan_nhan_vien_cccd_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.MoiQuanHe", "MoiQuanHe")
                        .WithMany("ThanNhanNhanViens")
                        .HasForeignKey("IdMqh")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("than_nhan_nhan_vien_id_mqh_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.ThanNhan", "ThanNhan")
                        .WithMany("ThanNhanNhanViens")
                        .HasForeignKey("MaDinhDanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("than_nhan_nhan_vien_ma_dinh_danh_fkey");

                    b.Navigation("MoiQuanHe");

                    b.Navigation("NhanVien");

                    b.Navigation("ThanNhan");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.BacLuong", b =>
                {
                    b.Navigation("QuyetDinhNhanSus");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ChucVu", b =>
                {
                    b.Navigation("ChucVuCapDuois");

                    b.Navigation("KhungNangLucs");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.KyDanhGia", b =>
                {
                    b.Navigation("PhieuDanhGias");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.MoiQuanHe", b =>
                {
                    b.Navigation("ThanNhanNhanViens");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NgachLuong", b =>
                {
                    b.Navigation("BacLuongs");

                    b.Navigation("ChucVus");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhanVien", b =>
                {
                    b.Navigation("HopDongLaoDongs");

                    b.Navigation("NhatKyTrangThais");

                    b.Navigation("QuyetDinhNhanSus");

                    b.Navigation("ThanNhanNhanViens");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.PhieuDanhGiaNangLuc", b =>
                {
                    b.Navigation("ChiTietDanhGias");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiKhoan", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ThanNhan", b =>
                {
                    b.Navigation("ThanNhanNhanViens");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
