// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayrollManagementSystem.Infrastructure.Persistence;

#nullable disable

namespace PayrollManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525124928_AddEmployeeManagementModels")]
    partial class AddEmployeeManagementModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.BacLuong", b =>
                {
                    b.Property<string>("IdBacLuong")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_bac_luong");

                    b.Property<string>("IdChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_chuc_vu");

                    b.Property<decimal>("LuongP1")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("luong_p1");

                    b.Property<DateOnly>("NgayApDung")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ap_dung");

                    b.HasKey("IdBacLuong")
                        .HasName("bac_luongs_pkey");

                    b.HasIndex("IdChucVu");

                    b.ToTable("bac_luongs", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ChucVu", b =>
                {
                    b.Property<string>("IdChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_chuc_vu");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_chuc_vu");

                    b.HasKey("IdChucVu")
                        .HasName("chuc_vus_pkey");

                    b.ToTable("chuc_vus", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.HopDongLaoDong", b =>
                {
                    b.Property<string>("SoHopDong")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_hop_dong");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("loai_hop_dong");

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("luong_co_ban");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("SoHopDong")
                        .HasName("hop_dong_lao_dongs_pkey");

                    b.HasIndex("Cccd");

                    b.ToTable("hop_dong_lao_dongs", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.MoiQuanHe", b =>
                {
                    b.Property<Guid>("IdMqh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_mqh")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("TenQuanHe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_quan_he");

                    b.HasKey("IdMqh")
                        .HasName("moi_quan_hes_pkey");

                    b.ToTable("moi_quan_hes", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NganHang", b =>
                {
                    b.Property<Guid>("IdNganHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_ngan_hang")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ten_ngan_hang");

                    b.HasKey("IdNganHang")
                        .HasName("ngan_hangs_pkey");

                    b.ToTable("ngan_hangs", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhanVien", b =>
                {
                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chuyen_nganh");

                    b.Property<string>("DanToc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dan_toc");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("boolean")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("IdPb")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_pb");

                    b.Property<Guid?>("IdTaiKhoan")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tai_khoan");

                    b.Property<DateOnly?>("NgayNghiViec")
                        .HasColumnType("date")
                        .HasColumnName("ngay_nghi_viec");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateOnly?>("NgayVaoLam")
                        .HasColumnType("date")
                        .HasColumnName("ngay_vao_lam");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("sdt");

                    b.Property<string>("SoBhxh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_bhxh");

                    b.Property<string>("SoBhyt")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_bhyt");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Cccd")
                        .HasName("nhan_viens_pkey");

                    b.HasIndex("IdPb");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "nhan_viens_email_key")
                        .IsUnique();

                    b.ToTable("nhan_viens", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhatKyTrangThai", b =>
                {
                    b.Property<Guid>("IdNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_nhat_ky")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ly_do");

                    b.Property<DateTime>("NgayThayDoi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_thay_doi");

                    b.Property<string>("NguoiThayDoi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nguoi_thay_doi");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai_cu");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai_moi");

                    b.HasKey("IdNhatKy")
                        .HasName("nhat_ky_trang_thais_pkey");

                    b.HasIndex("Cccd");

                    b.ToTable("nhat_ky_trang_thais", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.PhongBan", b =>
                {
                    b.Property<string>("IdPb")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_pb");

                    b.Property<string>("TenPb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_pb");

                    b.HasKey("IdPb")
                        .HasName("phong_bans_pkey");

                    b.ToTable("phong_bans", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.QuyetDinhNhanSu", b =>
                {
                    b.Property<string>("SoQuyetDinh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("so_quyet_dinh");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("IdBacLuongMoi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_bac_luong_moi");

                    b.Property<string>("IdChucVuMoi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id_chuc_vu_moi");

                    b.Property<string>("LoaiQuyetDinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("loai_quyet_dinh");

                    b.Property<DateOnly?>("NgayHetHan")
                        .HasColumnType("date")
                        .HasColumnName("ngay_het_han");

                    b.Property<DateOnly>("NgayHieuLuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_hieu_luc");

                    b.Property<string>("NguoiKy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nguoi_ky");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("SoQuyetDinh")
                        .HasName("quyet_dinh_nhan_sus_pkey");

                    b.HasIndex("Cccd");

                    b.HasIndex("IdBacLuongMoi");

                    b.ToTable("quyet_dinh_nhan_sus", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_tai_khoan");

                    b.Property<bool?>("DangNhapLanDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("dang_nhap_lan_dau");

                    b.Property<Guid?>("IdVaiTro")
                        .HasColumnType("uuid")
                        .HasColumnName("id_vai_tro");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mat_khau_hash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ten_tai_khoan");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("IdTaiKhoan")
                        .HasName("tai_khoans_pkey");

                    b.HasIndex("IdVaiTro");

                    b.HasIndex(new[] { "TenTaiKhoan" }, "tai_khoans_ten_tai_khoan_key")
                        .IsUnique();

                    b.ToTable("tai_khoans", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiKhoanNganHang", b =>
                {
                    b.Property<string>("Stk")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stk");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("ChiNhanh")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chi_nhanh");

                    b.Property<Guid?>("IdNganHang")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ngan_hang");

                    b.Property<DateOnly?>("NgayMoThe")
                        .HasColumnType("date")
                        .HasColumnName("ngay_mo_the");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Stk")
                        .HasName("tai_khoan_ngan_hangs_pkey");

                    b.HasIndex("Cccd");

                    b.HasIndex("IdNganHang");

                    b.ToTable("tai_khoan_ngan_hangs", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiLieuNhanVien", b =>
                {
                    b.Property<Guid>("IdTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_tai_lieu")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duong_dan_file");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("loai_tai_lieu");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ngay_tai_len");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ten_tai_lieu");

                    b.HasKey("IdTaiLieu")
                        .HasName("tai_lieu_nhan_viens_pkey");

                    b.HasIndex("Cccd");

                    b.ToTable("tai_lieu_nhan_viens", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ThanNhan", b =>
                {
                    b.Property<string>("MaDinhDanh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ma_dinh_danh");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("TenTn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ten_tn");

                    b.HasKey("MaDinhDanh")
                        .HasName("than_nhans_pkey");

                    b.ToTable("than_nhans", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ThanNhanNhanVien", b =>
                {
                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("MaDinhDanh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ma_dinh_danh");

                    b.Property<Guid?>("IdMqh")
                        .HasColumnType("uuid")
                        .HasColumnName("id_mqh");

                    b.HasKey("Cccd", "MaDinhDanh")
                        .HasName("than_nhan_nhan_vien_pkey");

                    b.HasIndex("IdMqh");

                    b.HasIndex("MaDinhDanh");

                    b.ToTable("than_nhan_nhan_vien", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.VaiTro", b =>
                {
                    b.Property<Guid>("IdVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_vai_tro");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("IdVaiTro")
                        .HasName("vai_tros_pkey");

                    b.ToTable("vai_tros", (string)null);
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.BacLuong", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.ChucVu", "ChucVu")
                        .WithMany("BacLuongs")
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bac_luongs_id_chuc_vu_fkey");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.HopDongLaoDong", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("HopDongLaoDongs")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hop_dong_lao_dongs_cccd_fkey");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhanVien", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdPb")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("nhan_viens_id_pb_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("PayrollManagementSystem.Domain.Models.NhanVien", "IdTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("nhan_viens_id_tai_khoan_fkey");

                    b.Navigation("PhongBan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhatKyTrangThai", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("NhatKyTrangThais")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("nhat_ky_trang_thais_cccd_fkey");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.QuyetDinhNhanSu", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("QuyetDinhNhanSus")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("quyet_dinh_nhan_sus_cccd_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.BacLuong", "BacLuong")
                        .WithMany("QuyetDinhNhanSus")
                        .HasForeignKey("IdBacLuongMoi")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("quyet_dinh_nhan_sus_id_bac_luong_moi_fkey");

                    b.Navigation("BacLuong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiKhoan", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdVaiTro")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("tai_khoans_id_vai_tro_fkey");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiKhoanNganHang", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("TaiKhoanNganHangs")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("tai_khoan_ngan_hangs_cccd_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.NganHang", "NganHang")
                        .WithMany("TaiKhoanNganHangs")
                        .HasForeignKey("IdNganHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("tai_khoan_ngan_hangs_id_ngan_hang_fkey");

                    b.Navigation("NganHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiLieuNhanVien", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("TaiLieuNhanViens")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tai_lieu_nhan_viens_cccd_fkey");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ThanNhanNhanVien", b =>
                {
                    b.HasOne("PayrollManagementSystem.Domain.Models.NhanVien", "NhanVien")
                        .WithMany("ThanNhanNhanViens")
                        .HasForeignKey("Cccd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("than_nhan_nhan_vien_cccd_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.MoiQuanHe", "MoiQuanHe")
                        .WithMany("ThanNhanNhanViens")
                        .HasForeignKey("IdMqh")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("than_nhan_nhan_vien_id_mqh_fkey");

                    b.HasOne("PayrollManagementSystem.Domain.Models.ThanNhan", "ThanNhan")
                        .WithMany("ThanNhanNhanViens")
                        .HasForeignKey("MaDinhDanh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("than_nhan_nhan_vien_ma_dinh_danh_fkey");

                    b.Navigation("MoiQuanHe");

                    b.Navigation("NhanVien");

                    b.Navigation("ThanNhan");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.BacLuong", b =>
                {
                    b.Navigation("QuyetDinhNhanSus");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ChucVu", b =>
                {
                    b.Navigation("BacLuongs");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.MoiQuanHe", b =>
                {
                    b.Navigation("ThanNhanNhanViens");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NganHang", b =>
                {
                    b.Navigation("TaiKhoanNganHangs");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.NhanVien", b =>
                {
                    b.Navigation("HopDongLaoDongs");

                    b.Navigation("NhatKyTrangThais");

                    b.Navigation("QuyetDinhNhanSus");

                    b.Navigation("TaiKhoanNganHangs");

                    b.Navigation("TaiLieuNhanViens");

                    b.Navigation("ThanNhanNhanViens");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.TaiKhoan", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.ThanNhan", b =>
                {
                    b.Navigation("ThanNhanNhanViens");
                });

            modelBuilder.Entity("PayrollManagementSystem.Domain.Models.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
